### ISSUE TITLE
Social media help!

### ISSUE THREAD

**Issue by sethetter** [openwichita/help-wanted#1]
This would involve writing some short social media content promoting..

* Upcoming events on Twitter and Facebook
* Current projects and efforts
* Other local civic / tech related topics

Using a service like Buffer to queue up posts makes this much more manageable! Any help here is greatly appreciated.

**Comment by doshitan** [comment]
How much time do you currently spend managing social media for Open Wichita?

**Comment by sethetter** [comment]
I would say it could be taken care of with about an hour of work per week.
I've been bad about being consistent with it, haha.
